//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace POSDataModel
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class POSEntities : DbContext
    {
        public POSEntities()
            : base("name=POSEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<tbl_danhmuchanghoa> tbl_danhmuchanghoa { get; set; }
        public DbSet<tbl_hanghoa> tbl_hanghoa { get; set; }
        public DbSet<tbl_hoadon> tbl_hoadon { get; set; }
        public DbSet<tbl_khachhang> tbl_khachhang { get; set; }
        public DbSet<tbl_giamgia> tbl_giamgia { get; set; }
        public DbSet<tbl_chitiethoadon> tbl_chitiethoadon { get; set; }
    }
}
