//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace POSDataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_hoadon
    {
        public tbl_hoadon()
        {
            this.tbl_chitiethoadon = new HashSet<tbl_chitiethoadon>();
        }
    
        public int idhoadon { get; set; }
        public Nullable<System.DateTime> ngaylap { get; set; }
        public Nullable<double> tongtien { get; set; }
        public Nullable<int> idkhachhang { get; set; }
        public Nullable<byte> phuongthucthanhtoan { get; set; }
        public Nullable<bool> trangthaithanhtoan { get; set; }
        public Nullable<bool> mail { get; set; }
    
        public virtual tbl_khachhang tbl_khachhang { get; set; }
        public virtual ICollection<tbl_chitiethoadon> tbl_chitiethoadon { get; set; }
    }
}
