//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace POSDataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_hanghoa
    {
        public tbl_hanghoa()
        {
            this.tbl_giamgia = new HashSet<tbl_giamgia>();
            this.tbl_chitiethoadon = new HashSet<tbl_chitiethoadon>();
        }
    
        public int idhanghoa { get; set; }
        public string tenhanghoa { get; set; }
        public Nullable<double> dongia { get; set; }
        public string diachianh { get; set; }
        public Nullable<int> iddanhmuc { get; set; }
    
        public virtual tbl_danhmuchanghoa tbl_danhmuchanghoa { get; set; }
        public virtual ICollection<tbl_giamgia> tbl_giamgia { get; set; }
        public virtual ICollection<tbl_chitiethoadon> tbl_chitiethoadon { get; set; }
    }
}
