//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace POSDataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_khachhang
    {
        public tbl_khachhang()
        {
            this.tbl_hoadon = new HashSet<tbl_hoadon>();
        }
    
        public int idkhachhang { get; set; }
        public string tenkhachhang { get; set; }
        public string emai { get; set; }
        public string sodienthoai { get; set; }
        public string diachi { get; set; }
    
        public virtual ICollection<tbl_hoadon> tbl_hoadon { get; set; }
    }
}
