//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace POSDataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_danhmuchanghoa
    {
        public tbl_danhmuchanghoa()
        {
            this.tbl_hanghoa = new HashSet<tbl_hanghoa>();
        }
    
        public int iddanhmuc { get; set; }
        public string tendanhmuc { get; set; }
    
        public virtual ICollection<tbl_hanghoa> tbl_hanghoa { get; set; }
    }
}
